spring:
  application:
    name: @artifactId@
  profiles:
    include: dev
    #eureka权限配置
  security:
    basic:
      enabled: true
    user:
      name: root
      password: root
#eureka配置
#集群register-with-eureka|fetch-registry 为true
eureka:
  instance:
    hostname: eurekaserver.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
    server:
      #是否开启安全保护,默认是开启的,如果默认开启,注册中心的服务列表就算有些服务断开了,也会继续保存
      enable-self-preservation: false
      ##剔除失效服务间隔
      eviction-interval-timer-in-ms: 2000