server:
  port: 9200
#eureka客户端配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://zengling:zengling@localhost:8100/eureka/
#日志配置
logging:
  config: classpath:log4j2-dev.yml
app:
  id: @artifactId@
apollo:
  meta: http://13.13.13.58:8080